/* eslint-disable @typescript-eslint/no-unused-vars */
import {
  CrmAnalytics,
  Orders,
  Cryptocurrency,
  Banking,
  Personal,
  CmsAnalytics,
  Influencer,
  Travel,
  Teacher,
  Education,
  Authors,
  Doctors,
  Employees,
  Workspaces,
  Meetings,
  ProjectBoards,
  WidgetUi,
  WidgetContacts,
  Application,
  AiChatApp,
  ChatApp,
  FileManager,
  ToDoApp,
  TravelApp,
  JobsBoard,
  KanbanBoard,
  MailApp,
  NftAppV1,
  NftAppV2,
  PosSystem,
  Components,
  Accordion,
  Collapse,
  Tab,
  Dropdown,
  Popover,
  Modal,
  Drawer,
  Steps,
  Timeline,
  Pagination,
  MenuList,
  Treeview,
  Table,
  TableAdvanced,
  TableGridjs,
  Apexcharts,
  Carousel,
  Notification,
  Clipboard,
  Persist,
  MonochromeMode,
  FormLayoutV1,
  FormLayoutV2,
  FormLayoutV3,
  FormLayoutV4,
  FormLayoutV5,
  InputText,
  InputGroup,
  InputMask,
  Checkbox,
  Radio,
  Switch,
  Select,
  TomSelect,
  Textarea,
  Range,
  Datepicker,
  Timepicker,
  Datetimepicker,
  TextEditor,
  FormUpload,
  FormValidation,
  Elements,
  Avatar,
  Alert,
  Button,
  ButtonGroup,
  Badge,
  Breadcrumb,
  Card,
  Divider,
  Mask,
  Progress,
  Skeleton,
  Spinner,
  Tag,
  Tooltip,
  Forms,
  Typography,
} from "../pages";
const dashboardMoreMenuData = [
  {
    group: 1,
    menu: [
      {
        id: 1,
        title: "CRM Analytics",
        path: "crm-analytics",
        element: CrmAnalytics,
      },
      { id: 2, title: "Orders", path: "orders", element: Orders },
    ],
  },
  {
    group: 2,
    menu: [
      {
        id: 3,
        title: "Cryptocurrency",
        path: "cryptocurrency",
        element: Cryptocurrency,
      },
      { id: 4, title: "Banking", path: "banking", element: Banking },
      { id: 5, title: "Personal", path: "personal", element: Personal },
      {
        id: 6,
        title: "CMS Analytics",
        path: "cms-analytics",
        element: CmsAnalytics,
      },
      { id: 7, title: "Influencer", path: "influencer", element: Influencer },
      { id: 8, title: "Travel", path: "travel", element: Travel },
      { id: 9, title: "Teacher", path: "teacher", element: Teacher },
      { id: 10, title: "Education", path: "education", element: Education },
      { id: 11, title: "Authors", path: "authors", element: Authors },
      { id: 12, title: "Doctors", path: "doctors", element: Doctors },
      { id: 13, title: "Employees", path: "employees", element: Employees },
      { id: 14, title: "Workspaces", path: "workspaces", element: Workspaces },
      { id: 15, title: "Meetings", path: "meetings", element: Meetings },
      {
        id: 16,
        title: "Project Boards",
        path: "project-boards",
        element: ProjectBoards,
      },
    ],
  },
  {
    group: 3,
    menu: [
      { id: 17, title: "Widget UI", path: "widget-ui", element: WidgetUi },
      {
        id: 18,
        title: "Widget Contacts",
        path: "widget-contacts",
        element: WidgetContacts,
      },
    ],
  },
];

const applicationMoreMenuData = [
  {
    group: 4,
    menu: [
      { id: 19, title: "Chat App", path: "chat-app" },
      { id: 20, title: "AI Chat App", path: "ai-chat-app" },
      { id: 21, title: "Kanban Board", path: "kanban-board" },
      { id: 22, title: "File Manager", path: "file-manager" },
      { id: 23, title: "Mail App", path: "mail-app" },
      { id: 24, title: "Todo App", path: "todo-app" },
    ],
  },
  {
    group: 5,
    menu: [
      { id: 25, title: "NFT App v1", path: "nft-app-v1" },
      { id: 26, title: "NFT App v2", path: "nft-app-v2" },
      { id: 27, title: "POS System", path: "pos-system" },
      { id: 28, title: "Jobs Board", path: "jobs-board" },
      { id: 29, title: "Travel App", path: "travel-app" },
    ],
  },
];

const layoutsMenuData = [
  {
    group: 1,
    menu: [
      { id: 1, title: "Onboarding", path: "onboarding" },
      { id: 2, title: "User Card", path: "user-card" },
      { id: 3, title: "Blog Card", path: "blog-card" },
      { id: 4, title: "Help", path: "help" },
      { id: 5, title: "Price List", path: "price-list" },
      { id: 6, title: "Invoice", path: "invoice" },
    ],
  },
  {
    group: 2,
    menu: [
      { id: 7, title: "Sign In", path: "sign-in" },
      { id: 8, title: "Sign Up", path: "sign-up" },
    ],
  },
  {
    group: 3,
    menu: [
      { id: 9, title: "Error", path: "error" },
      { id: 10, title: "Starter", path: "starter" },
    ],
  },
];

const formMenuData = [
  {
    group: 1,
    menu: [
      { id: 1, title: "Form layout v1", path: "form-layout-v1" },
      { id: 2, title: "Form layout v2", path: "form-layout-v2" },
      { id: 3, title: "Form layout v3", path: "form-layout-v3" },
      { id: 4, title: "Form layout v4", path: "form-layout-v4" },
      { id: 5, title: "Form layout v5", path: "form-layout-v5" },
    ],
  },
  {
    group: 2,
    menu: [
      { id: 6, title: "Input text", path: "input-text" },
      { id: 7, title: "Input group", path: "input-group" },
      { id: 8, title: "Input mask", path: "input-mask" },
      { id: 9, title: "Checkbox", path: "checkbox" },
      { id: 10, title: "Radio", path: "radio" },
      { id: 11, title: "Switch", path: "switch" },
      { id: 12, title: "Select", path: "select" },
      { id: 13, title: "Tom select", path: "tom-select" },
      { id: 14, title: "Textarea", path: "textarea" },
      { id: 15, title: "Range", path: "range" },
      { id: 16, title: "Datepicker", path: "datepicker" },
      { id: 17, title: "Timepicker", path: "timepicker" },
      { id: 18, title: "Datetimepicker", path: "datetimepicker" },
      { id: 19, title: "Text editor", path: "text-editor" },
      { id: 20, title: "Form upload", path: "form-upload" },
      { id: 21, title: "Form validation", path: "form-validation" },
    ],
  },
];

const componentsMenuData = [
  {
    group: 1,
    menu: [
      { id: 1, element: Accordion, title: "Accordion", path: "accordion" },
      { id: 2, element: Collapse, title: "Collapse", path: "collapse" },
      { id: 3, element: Tab, title: "Tab", path: "tab" },
      { id: 4, element: Dropdown, title: "Dropdown", path: "dropdown" },
      { id: 5, element: Popover, title: "Popover", path: "popover" },
      { id: 6, element: Modal, title: "Modal", path: "modal" },
      { id: 7, element: Drawer, title: "Drawer", path: "drawer" },
      { id: 8, element: Steps, title: "Steps", path: "steps" },
      { id: 9, element: Timeline, title: "Timeline", path: "timeline" },
      { id: 10, element: Pagination, title: "Pagination", path: "pagination" },
      { id: 11, element: MenuList, title: "Menu list", path: "menu-list" },
      { id: 12, element: Treeview, title: "Treeview", path: "treeview" },
    ],
  },
  {
    group: 2,
    menu: [
      { id: 13, element: Table, title: "Table", path: "table" },
      {
        id: 14,
        element: TableAdvanced,
        title: "Table Advanced",
        path: "table-advanced",
      },
      {
        id: 15,
        element: TableGridjs,
        title: "Table Gridjs",
        path: "table-gridjs",
      },
    ],
  },
  {
    group: 3,
    menu: [
      { id: 16, element: Apexcharts, title: "Apexcharts", path: "apexcharts" },
      { id: 17, element: Carousel, title: "Carousel", path: "carousel" },
      {
        id: 18,
        element: Notification,
        title: "Notification",
        path: "notification",
      },
    ],
  },
  {
    group: 4,
    menu: [
      { id: 19, element: Clipboard, title: "Clipboard", path: "clipboard" },
      { id: 20, element: Persist, title: "Persist", path: "persist" },
      {
        id: 21,
        element: MonochromeMode,
        title: "Monochrome mode",
        path: "monochrome-mode",
      },
    ],
  },
];

const elementsMenuData = [
  {
    group: 1,
    menu: [
      { element: Avatar, id: 1, title: "Avatar", path: "avatar" },
      { element: Alert, id: 2, title: "Alert", path: "alert" },
      { element: Button, id: 3, title: "Button", path: "button" },
      {
        element: ButtonGroup,
        id: 4,
        title: "Button group",
        path: "button-group",
      },
      { element: Badge, id: 5, title: "Badge", path: "badge" },
      { element: Breadcrumb, id: 6, title: "Breadcrumb", path: "breadcrumb" },
      { element: Card, id: 7, title: "Card", path: "card" },
      { element: Divider, id: 8, title: "Divider", path: "divider" },
      { element: Mask, id: 9, title: "Mask", path: "mask" },
      { element: Progress, id: 10, title: "Progress", path: "progress" },
      { element: Skeleton, id: 11, title: "Skeleton", path: "skeleton" },
      { element: Spinner, id: 12, title: "Spinner", path: "spinner" },
      { element: Tag, id: 13, title: "Tag", path: "tag" },
      { element: Tooltip, id: 14, title: "Tooltip", path: "tooltip" },
    ],
  },
  {
    group: 2,
    menu: [
      { element: Forms, id: 15, title: "Forms", path: "forms", to: "/forms" },
      { element: Typography, id: 16, title: "Typography", path: "typography" },
    ],
  },
];

export {
  dashboardMoreMenuData,
  applicationMoreMenuData,
  formMenuData,
  layoutsMenuData,
  componentsMenuData,
  elementsMenuData,
};
